update

diff --git a/bin/setup-magento b/bin/setup-magento
--- a/bin/setup-magento
+++ b/bin/setup-magento
@@ -1,13 +1,66 @@
 #!/bin/bash
 set -o errexit
+# shellcheck source=../env/db.env
+source rds.env
+# shellcheck source=../env/elasticsearch.env
+source elasticsearch.env
+# shellcheck source=../env/magento.env
+source magento.env
+# shellcheck source=../env/rabbitmq.env
+source rmq.env
 
-[ -z "$1" ] && echo "Please specify a domain name (ex. magento.test)" && exit
+DOMAIN=${1:-magento.test}
 
-DOMAIN=$1
+#bin/stop
+#
+#docker-compose -f docker-compose.yml up -d
+#[ $? != 0 ] && echo "Failed to start Docker services" && exit
 
-if ! grep -q "$DOMAIN" /etc/hosts; then
-    echo "Your system password is needed to add an entry to /etc/hosts..."
-    echo "127.0.0.1 ::1 $DOMAIN" | sudo tee -a /etc/hosts
-fi
 
-#bin/setup-ssl "$DOMAIN"
+sleep 5
+
+bin/phpfpm-cli bin/magento setup:install \
+  --db-host="$MYSQL_ROOT_HOST" \
+  --db-name="$MYSQL_DATABASE" \
+  --db-user="$MYSQL_USER" \
+  --db-password="$MYSQL_PASSWORD" \
+  --base-url=https://"$DOMAIN"/ \
+  --base-url-secure=https://"$DOMAIN"/ \
+  --backend-frontname="$MAGENTO_ADMIN_FRONTNAME" \
+  --admin-firstname="$MAGENTO_ADMIN_FIRST_NAME" \
+  --admin-lastname="$MAGENTO_ADMIN_LAST_NAME" \
+  --admin-email="$MAGENTO_ADMIN_EMAIL" \
+  --admin-user="$MAGENTO_ADMIN_USER" \
+  --admin-password="$MAGENTO_ADMIN_PASSWORD" \
+  --language="$MAGENTO_LOCALE" \
+  --currency="$MAGENTO_CURRENCY" \
+  --timezone="$MAGENTO_TIMEZONE" \
+  --amqp-host="$RABBITMQ_HOST" \
+  --amqp-port="$RABBITMQ_PORT" \
+  --amqp-user="$RABBITMQ_DEFAULT_USER" \
+  --amqp-password="$RABBITMQ_DEFAULT_PASS" \
+  --amqp-virtualhost="$RABBITMQ_DEFAULT_VHOST" \
+  --cache-backend=redis \
+  --cache-backend-redis-server=redis \
+  --cache-backend-redis-db=0 \
+  --page-cache=redis \
+  --page-cache-redis-server=redis \
+  --page-cache-redis-db=1 \
+  --session-save=redis \
+  --session-save-redis-host=redis \
+  --session-save-redis-log-level=4 \
+  --session-save-redis-db=2 \
+  --search-engine=elasticsearch7 \
+  --elasticsearch-host=$ES_HOST \
+  --elasticsearch-port=$ES_PORT \
+  --use-rewrites=1 \
+  --no-interaction
+
+
+bin/magento setup:static-content:deploy -f
+bin/magento indexer:reindex
+bin/magento cache:flush
+bin/magento cron:install
+bin/magento deploy:mode:set developer
+
+echo "You may now access your Magento instance at https://${DOMAIN}/"
